[theme]
primaryColor = "#1e6fa0"
backgroundColor = "#faf6ef"
secondaryBackgroundColor = "#fdfaf3"
textColor = "#1a2530"
font = "sans serif"
base = "light"

[browser]
gatherUsageStats = false

[server]
runOnSave = false
