[theme]
primaryColor = "#005c95"
backgroundColor = "#fcfdfe"
secondaryBackgroundColor = "#f1f7fa"
textColor = "#0c2d42"
font = "sans serif"
base = "light"

[browser]
gatherUsageStats = false

[server]
runOnSave = false
